name: formula1_data
description: "A Dart package for retrieving Formula1™ data, such as races, drivers, results, and standings."
version: 2.0.0
repository: https://github.com/own-world-grp/formula1_data
homepage: https://techolve.org/formula1_data
issue_tracker: https://github.com/own-world-grp/formula1_data/issues
topics:
  - formula1
  - motorsport

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.7.0
  logger: ^2.4.0

dev_dependencies:
  lints: ^6.0.0
  mockito: ^5.8.1
  build_runner: ^2.16.1
  test: ^1.32.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
